[project]
name = "levenshtein-py"
dynamic = ["version"]
description = "Default template for PDM package"
authors = [{ name = "Dmitry Erlikh", email = "derlih@gmail.com" }]
dependencies = []
requires-python = ">=3.8"
readme = "README.md"
license = { text = "MIT" }

[build-system]
requires = ["pdm-backend", "distutils"]
build-backend = "pdm.backend"

[tool.pdm.version]
source = "file"
path = "src/levenshtein_py/__init__.py"

[tool.pdm.build]
run-setuptools = true

[tool.pdm.dev-dependencies]
test = ["pytest>=8.2.2"]
lint = ["pre-commit>=3.5.0", "mypy>=1.10.1"]
benchmark = [
    "pylev>=1.4.0",
    "Levenshtein>=0.25.1",
    "python-Levenshtein>=0.25.1",
    "leven>=1.0.4",
]

[tool.pdm.scripts]
test = "pytest"
lint = "pre-commit run --all-files"
mypy = "mypy src"
benchmark = "python benchmark.py"

[tool.mypy]
strict = true
exclude = ["tests"]
