name: Get Python version
outputs:
  python-version:
    description: "Python version"
    value: ${{ steps.get-python-version.outputs.python-version }}

runs:
  using: "composite"
  steps:
    - name: Get python version
      id: get-python-version
      shell: bash
      run: python .github/actions/get-python-version/action.py
