name: Update prek
on:
  schedule:
    - cron: "0 12 * * 0"
jobs:
  prek-update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
          ref: main
      - name: Install python
        uses: actions/setup-python@v6
        id: setup-python
        with:
          python-version: 3.14
      - name: Install prek
        run: pip install prek
      - name: Run prek auto-update
        run: prek auto-update
      - name: Restore prek hooks
        uses: actions/cache@v5
        with:
          path: ~/.cache/prek
          key: prek-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run prek hooks
        run: prek run --all-files
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.REPO_PAT }}
          branch: update/prek-autoupdate-${{ github.run_id }}
          title: Auto-update prek hooks
          commit-message: Auto-update prek hooks
      - name: Automerge commit
        if: ${{ steps.create-pr.outputs.pull-request-number }}
        run: gh pr merge "${PR_NUMBER}" --auto --squash --delete-branch
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ steps.create-pr.outputs.pull-request-number }}
