name: Update pre-commit
on:
  schedule:
    - cron: '0 12 * * 0'
jobs:
  pre-commit-update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: main
      - name: Install python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: 3.13
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate
      - name: Restore pre-commit hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run pre-commit hooks
        run: pre-commit run --all-files
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.REPO_PAT }}
          branch: update/pre-commit-autoupdate-${{ github.run_id }}
          title: Auto-update pre-commit hooks
          commit-message: Auto-update pre-commit hooks
      - name: Automerge commit
        if: ${{ steps.create-pr.outputs.pull-request-number }}
        run: gh pr merge ${{ steps.create-pr.outputs.pull-request-number }} --auto --squash --delete-branch
        env:
          GH_TOKEN: ${{ github.token }}
